/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvatarEditorDialog: typeof import('./src/components/chat/dialog/AvatarEditorDialog.vue')['default']
    BottomMenuComponent: typeof import('./src/components/sidebar/BottomMenuComponent.vue')['default']
    CAnimationTabs: typeof import('./src/components/base/tab/CAnimationTabs.vue')['default']
    CBaseDialog: typeof import('./src/components/base/dialog/CBaseDialog.vue')['default']
    CDialog: typeof import('./src/components/base/dialog/CDialog.vue')['default']
    ChatBotItem: typeof import('./src/components/sidebar/ChatBotItem.vue')['default']
    ChatBotListComponent: typeof import('./src/components/sidebar/ChatBotListComponent.vue')['default']
    ChatBubbleMessageItem: typeof import('./src/components/chat/block/ChatBubbleMessageItem.vue')['default']
    ChatGptSettingsList: typeof import('./src/components/setting/chat/ChatGptSettingsList.vue')['default']
    ChatInputComponent: typeof import('./src/components/chat/block/ChatInputComponent.vue')['default']
    ChatMessagesListComponent: typeof import('./src/components/chat/block/ChatMessagesListComponent.vue')['default']
    ChatNormalMessageItem: typeof import('./src/components/chat/block/ChatNormalMessageItem.vue')['default']
    ChatTabsComponent: typeof import('./src/components/chat/block/ChatTabsComponent.vue')['default']
    ChatTemplateInfoDialog: typeof import('./src/components/chat/dialog/ChatTemplateInfoDialog.vue')['default']
    CListItem: typeof import('./src/components/base/list/CListItem.vue')['default']
    CTabPane: typeof import('./src/components/base/tab/CTabPane.vue')['default']
    CTabs: typeof import('./src/components/base/tab/CTabs.vue')['default']
    CTopNavBar: typeof import('./src/components/base/nav/CTopNavBar.vue')['default']
    DallESettingsList: typeof import('./src/components/setting/chat/DallESettingsList.vue')['default']
    EditMessageDialog: typeof import('./src/components/chat/dialog/EditMessageDialog.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GeminiSettingsList: typeof import('./src/components/setting/chat/GeminiSettingsList.vue')['default']
    HomeChatComponent: typeof import('./src/components/chat/block/HomeChatComponent.vue')['default']
    KeyMapChangeDialog: typeof import('./src/components/setting/dialog/KeyMapChangeDialog.vue')['default']
    MessageMarkdownComponent: typeof import('./src/components/chat/block/MessageMarkdownComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarComponent: typeof import('./src/components/sidebar/SideBarComponent.vue')['default']
    SlideSideBarComponent: typeof import('./src/components/sidebar/SlideSideBarComponent.vue')['default']
    TheKeyMapCode: typeof import('./src/components/base/list/TheKeyMapCode.vue')['default']
  }
}
